heymax:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: ../../data/warehouse/heymax.duckdb
      schema: dbt
      threads: 1
    prod:
      type: duckdb
      path: ../../data/warehouse/heymax.duckdb
      schema: ''
      threads: 1
    ci:
      type: duckdb
      path: ../../data/warehouse/heymax.duckdb
      schema: ci
      threads: 1