name: DBT Slim CI

on:
  pull_request:
    branches: [ "main" ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          cd dbt/heymax/          
          dbt deps

      - name: Download Production Manifest
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: save_prod_manifest.yml 
          name: dbt-manifest
          branch: main
          path: ./dbt/heymax/state/
          search_artifacts: true 
          if_no_artifact_found: warn

      - name: DuckDB setup - Create heymax.duckdb and ingest data
        run: python ${{ github.workspace }}/scripts/ingest_data.py

      - name: Slim CI Build
        run: |
          cd dbt/heymax/
          if [ -f "./state/manifest.json" ]; then
            echo "Manifest found. Running Slim CI on modified models..."
            dbt build --select state:modified+ --exclude tag:post_build_tests --state ./state 
            dbt test --select state:modified+ tag:post_build_tests
          else
            echo "No manifest found. Running full CI build..."
            dbt build --exclude tag:post_build_tests
            dbt test --select tag:post_build_tests
          fi