name: Save Production Manifest for GH Pages
on:
  push:
    branches: [ "main" ]
  
  workflow_dispatch:

jobs:
  archive_manifest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Generate Manifest
        run: |
          cd dbt/heymax/
          dbt deps
          dbt compile --profiles-dir .

      - name: Upload Manifest Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dbt-manifest
          path: dbt/heymax/target/manifest.json 
          retention-days: 14
