name: Save Production Manifest for GH Pages
on:
  push:
    branches: [ "main" ]

jobs:
  archive_manifest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Generate Manifest
        # We don't need to run data, just compile the project logic
        run: 
          cd dbt/heymax/
          dbt compile 

      - name: Upload Manifest Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dbt-manifest
          path: .dbt/heymax/target/manifest.json # dbt always puts manifest.json here
          retention-days: 14